### ISSUE TITLE
fatal: clone of 'git://sourceware.org/git/newlib-cygwin.git

### ISSUE THREAD

**Issue by maz-s** [johnwinans/riscv-toolchain-install-guide#1]
Hi,
when I run **./buildall.sh**, I saw this error:
Fatal: clone of 'git://sourceware.org/git/newlib-cygwin.git' into submodule path '/home/project/riscv/riscv-toolchain-install-guide/riscv-gnu-toolchain/riscv-newlib' failed
Failed to clone 'riscv-newlib'. Retry scheduled
Cloning into '/home/maz/project/riscv/riscv-toolchain-install-guide/riscv-gnu-toolchain/riscv-newlib'...
fatal: unable to connect to sourceware.org:
sourceware.org[0: 8.43.85.97]: errno=Connection refused
sourceware.org[1: 2620:52:3:1:0:246e:9693:128c]: errno=Network is unreachable

I use Ubuntu 64-bit 20.04.3, and I run it in VMware Fusion..'

**Comment by benner** [comment]
It seems like it was temporary problem with sourceware.org or your internet connection. Please try again :-)

**Comment by maz-s** [comment]
I have tried several times with different internet connections.

**Comment by benner** [comment]
![image](https://user-images.githubusercontent.com/407369/136972456-6463d5f6-0a6e-40c4-bd5a-a2efe29738fa.png)

**Comment by maz-s** [comment]
<img width="743" alt="Screenshot 2021-10-12 at 16 24 13" src="https://user-images.githubusercontent.com/84074995/136974601-cf7a2191-9ec3-4773-8ffb-d70768db7ba5.png">

**Comment by johnwinans** [comment]
I assume this resolved itself -- as some sort of transient network outage.  If problems persist, please open another issue.
