### ISSUE TITLE
Removing the riscv32 toolchain

### ISSUE THREAD

**Issue by kamina-san** [johnwinans/riscv-toolchain-install-guide#2]
How can you remove the riscv32 toolchain? seems I've run with some trouble when i want to install spike and I can't find how to remove it.

**Comment by johnwinans** [comment]
Be careful this message includes irreversible file removal advice.  I assume you are able to read and understand this ENTIRE message before blindly running remove commands!

If you installed it like I did, you can probably just remove it from your PATH to stop it from being used.

If you want to files gone then go to where you cloned the repos for all the parts and simply delete them.

If you installed them EXACTLY like I did and discussed in this site and corresponding video (in a projects/riscv directory in your home directory) then you can do this to remove the files that were built/installed:

  rm -rf ${HOME}/projects/riscv/install

Or you can do this to delete all of the riscv files including the entire source code and the installed code. (I /only/ recommend this if you did NOT create your own source code and test files in the same directory tree as the cloned repos!)

  rm -rf ${HOME}/projects/riscv/

**Comment by kamina-san** [comment]
That was fast! 
Unfortunately I didn't EXACTLY installed it like you did, and since I am a pretty big noob with Linux I guess I did some pretty dubious things. I use Virtual box on windows to run linux so now I make a new Ubuntu installation since it was too much of a hassle to untangle the mess I put myself in. 
I will keep in mind your directions for next time! (the which riscv32-unknown-elf-as showed me it was running from the root/bin)

**Comment by johnwinans** [comment]
Well, that is why we have virtual machines!
:-D
